name: personal_expenses
description: "This financial app your expenses based on ewerton's personal expenses"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: any
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.2
  path: ^1.8.3
  easy_pie_chart: ^1.0.0
  fl_chart: ^0.68.0
  social_share: ^2.3.1
  flutter_native_splash: ^1.1.8+4
  flutter_launcher_icons: ^0.9.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#00BF63"
  image: assets/splash_icon.png
  android: true

flutter_icons:
  android: "ic_launcher"
  image_path: "assets/icons/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/cats_icon.png
    - assets/icons/compras_icon.png
    - assets/icons/mercado_icon.png
    - assets/icons/merenda_icon.png
    - assets/icons/meal_icon.png
    - assets/icons/home_icon.png
    - assets/icons/general_icon.png
    - assets/icons/reserva_icon.png
    - assets/icons/divided_icon.png
    - assets/icons/users_icon.png
    - assets/icons/pin_icon.png
